services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
      # - 3307:3306
    networks:
      - nw-db
    restart: always

  backend:
    build: 
      context: ./my-server-express
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - database
    networks:
      - nw-server
      - nw-db
    restart: always

  frontend:
    build:
      context: ./my-client-react
      dockerfile: Dockerfile
    # ports:
    #   - 8888:80
    networks:
      - nw-client
    restart: always

  proxy:
    build: ./my-proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
      - nw-client
      - nw-server
    restart: always
 
volumes:
  mysql_data:

networks:
  nw-client:
  nw-server:
  nw-db: